#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

$rise = $HYPR_SCRIPT_DIR/rise.sh

exec-once = systemctl --user start hyprpolkitagent
exec-once = $terminal
exec-once = waybar & hyprpaper &
exec-once = swaync & # Notification Daemon

$notif_script = $HYPR_SCRIPT_DIR/notify-me.sh
exec-once = $notif_script || $rise "[hypr/auto-start] could not load notification services"

exec-once = thunderbird
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = [workspace 0 silent] flatpak run org.mozilla.Thunderbird com.ulduzsoft.Birdtray &
exec-once = [workspace 9 silent] flatpak run com.rtosta.zapzap &
