# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

$HYPR_CONFIG_DIR=$HOME/.config/hypr
$HYPR_SOURCE_DIR=$HYPR_CONFIG_DIR/sources
$HYPR_SCRIPT_DIR=$HYPR_CONFIG_DIR/scripts

source = $HYPR_SOURCE_DIR/variable.conf
source = $HYPR_SOURCE_DIR/animation.conf
source = $HYPR_SOURCE_DIR/auto-start.conf
source = $HYPR_SOURCE_DIR/bindings.conf
source = $HYPR_SOURCE_DIR/w-rules.conf
source = $HYPR_SOURCE_DIR/general.conf

# HyprMod managed settings
source = ~/.config/hypr/hyprland-gui.conf
